#!/usr/bin/env bash
# Writes repo-root `.env` so `docker compose` picks up the same `LOGISTICS_*` as local (substitution in docker-compose.e2e.yml).
# In GitHub Actions, job `env` / secrets must be exported before this script runs. Uses demo defaults when a secret is unset.
# Do not `cat` this file in logs — values are credentials.
set -euo pipefail
ROOT="${GITHUB_WORKSPACE:-$(pwd)}"
cd "$ROOT"

U="${LOGISTICS_UI_USER_NAME:-pet@example.com}"
P="${LOGISTICS_PASSWORD:-pet-secret}"
AU="${LOGISTICS_ADMIN_USER_NAME:-pet-admin@example.com}"
AP="${LOGISTICS_ADMIN_PASSWORD:-pet-admin-secret}"
CU="${LOGISTICS_ACCOUNTANT_USER_NAME:-pet-accountant@example.com}"
CP="${LOGISTICS_ACCOUNTANT_PASSWORD:-pet-accountant-secret}"
CLIENT="${LOGISTICS_BASE_CLIENT_URL:-http://localhost:5173/}"
API="${LOGISTICS_BASE_API_URL:-http://localhost:5173/api}"
LOGIN_FIELD="${E2E_LOGIN_USER_FIELD_NAME:-identifier}"
TZ="${E2E_TIME_ZONE:-UTC}"

OUT=".env"
rm -f "$OUT"
{
  echo "# Generated by .github/scripts/ci/write-docker-e2e-env.sh — do not commit (see .gitignore)."
  printf '%s=%s\n' 'LOGISTICS_BASE_CLIENT_URL' "$CLIENT"
  printf '%s=%s\n' 'LOGISTICS_BASE_API_URL' "$API"
  printf '%s=%s\n' 'LOGISTICS_UI_USER_NAME' "$U"
  printf '%s=%s\n' 'LOGISTICS_PASSWORD' "$P"
  printf '%s=%s\n' 'LOGISTICS_ADMIN_USER_NAME' "$AU"
  printf '%s=%s\n' 'LOGISTICS_ADMIN_PASSWORD' "$AP"
  printf '%s=%s\n' 'LOGISTICS_ACCOUNTANT_USER_NAME' "$CU"
  printf '%s=%s\n' 'LOGISTICS_ACCOUNTANT_PASSWORD' "$CP"
  printf '%s=%s\n' 'E2E_LOGIN_USER_FIELD_NAME' "$LOGIN_FIELD"
  printf '%s=%s\n' 'E2E_TIME_ZONE' "$TZ"
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines) for Docker Compose substitution."
